{
 "title": "KPI - QUALITOR",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CONSULTA ${__from:date:YYYY-MM-DD} 00:00:00 ATÈ ${__to:date:YYYY-MM-DD} 23:59:59\n<p style=\"text-align: center\"\"font-size:8px\"><img src=\"https://blog.qualitor.com.br/wp-content/uploads/2019/11/logo-qualitor-branco.png\" width=\"250\" class=\"center\"/></p>\n"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GERAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "EM ATENDIMENTO",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*)\r\nFROM hd_chamado hc\r\njoin hd_situacao hs on(hs.cdsituacao = hc.cdsituacao)\r\njoin hd_tipochamado ht on(ht.cdtipochamado = hc.cdtipochamado)\r\njoin hd_localidade loc on(loc.cdlocalidade = hc.cdlocalidade) \r\nwhere 1=1\r\nand hc.cdsituacao = '3'"
      }
     ]
    },
    {
     "title": "CANCELADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(distinct(cham.cdchamado))\nfrom hd_chamado cham \njoin hd_situacao hs on(hs.cdsituacao = cham.cdsituacao)\njoin hd_localidade loc on(loc.cdlocalidade = cham.cdlocalidade) \njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado) \nwhere 1=1\nand cham.dtchamado BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hs.cdsituacao = 8"
      }
     ]
    },
    {
     "title": "ATRASADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(DISTINCT(cham.cdchamado))\r\nfrom hd_chamado cham \r\njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \r\njoin ad_cliente c on (c.cdcliente=cham.cdcliente) \r\nwhere 1=1 \r\nand cdsituacao in ('3','2') \r\nand DATEDIFF(mi,cham.dtprevisaotermino,CURRENT_TIMESTAMP) > 0"
      }
     ]
    },
    {
     "title": "SUSPENSOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*)\r\nFROM hd_chamado hc\r\njoin hd_situacao hs on(hs.cdsituacao = hc.cdsituacao)\r\njoin hd_tipochamado ht on(ht.cdtipochamado = hc.cdtipochamado)\r\njoin hd_localidade loc on(loc.cdlocalidade = hc.cdlocalidade) \r\nwhere 1=1\r\nand hc.cdsituacao = '5'"
      }
     ]
    },
    {
     "title": "AGUARD ATEND",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(DISTINCT(cham.cdchamado)) \r\nfrom hd_chamado cham join ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \r\njoin ad_cliente c on (c.cdcliente=cham.cdcliente) \r\njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado)\r\nwhere 1=1 and cham.cdsituacao = '2'"
      }
     ]
    },
    {
     "title": "ENCERRADOS ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(distinct(cham.cdchamado))\nfrom hd_chamado cham \njoin hd_situacao hs on(hs.cdsituacao = cham.cdsituacao)\njoin hd_localidade loc on(loc.cdlocalidade = cham.cdlocalidade) \njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado) \nwhere 1=1\nand cham.dtchamado BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hs.cdsituacao = 7\t"
      }
     ]
    },
    {
     "title": "ITERACAO",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(DISTINCT(cham.cdchamado))\r\nfrom hd_chamado cham join ad_usuario usu on (usu.cdusuario=cham.cdresponsavel)\r\njoin ad_cliente c on (c.cdcliente=cham.cdcliente)\r\njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado)\r\nwhere 1=1 and cham.cdsituacao in ('3','5') and fgchamadoreaberto IS NOT NULL"
      }
     ]
    }
   ]
  },
  {
   "title": "IMPLANTAÇÂO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "IMPLANTAÇÃO ENCERRADAS",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "select\ncdchamado as \"CHAMADO\",\nCASE\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6) like '%[0-9][0-9].[0-9][0-9][0-9]%' then SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6)\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6) like '%[0-9][0-9][0-9][0-9][0-9]%' then SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6)\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6) not like '%[0-9][0-9].[0-9][0-9][0-9]%' then 'SEM OP'\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6) not like '%[0-9][0-9][0-9][0-9][0-9]%' then 'SEM OP'\nEND as OP,\nnmcliente as \"EMPRESA\",\nnmtitulochamado as \"TITULO\",\nSUBSTRING(nmcategoria, 15, 100) as \"CATEGORIA\",\nCONVERT(date, dtchamado) as \"ABERTURA\",\nnmusuario as \"RESPONSAVEL\"\n\nfrom hd_chamado\ninner join ad_cliente on ad_cliente.cdcliente = hd_chamado.cdcliente\ninner join hd_categoria on hd_categoria.cdcategoria = hd_chamado.cdcategoria\ninner join ad_usuario on ad_usuario.cdusuario = hd_chamado.cdresponsavel\n\nwhere dttermino BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand cdsituacao = '7'\nand hd_categoria.cdcategoriasuperior = '1098'\norder by cdchamado"
      }
     ]
    },
    {
     "title": "IMPLANTAÇÃO X CATEGORIA",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select hd_categoria.nmcategoria as \"CATEGORIA\",\ncount(cdchamado) as \"QUANTIDADE\"\nfrom hd_chamado\ninner join hd_categoria on hd_categoria.cdcategoria = hd_chamado.cdcategoria\nwhere dttermino BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hd_categoria.cdcategoriasuperior = '1098'\nand cdsituacao = '7'\ngroup by hd_categoria.nmcategoria"
      }
     ]
    },
    {
     "title": "IMPLANTAÇÃO EM ATENDIMENTO",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "select\ncdchamado as CHAMADO,\nCASE\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6) like '%[0-9][0-9].[0-9][0-9][0-9]%' then SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6)\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6) like '%[0-9][0-9][0-9][0-9][0-9]%' then SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6)\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9].[0-9][0-9][0-9]%', nmtitulochamado), 6) not like '%[0-9][0-9].[0-9][0-9][0-9]%' then 'SEM OP'\n\tWHEN SUBSTRING(nmtitulochamado, PATINDEX('%[0-9][0-9][0-9][0-9][0-9]%', nmtitulochamado), 6) not like '%[0-9][0-9][0-9][0-9][0-9]%' then 'SEM OP'\nEND as OP,\nnmcliente as EMPRESA,\nnmtitulochamado as TITULO,\nSUBSTRING(nmcategoria, 15, 100) as CATEGORIA,\nCONVERT(date, dtchamado) as ABERTURA,\nnmusuario as RESPONSAVEL\nfrom hd_chamado\ninner join ad_cliente on ad_cliente.cdcliente = hd_chamado.cdcliente\ninner join hd_categoria on hd_categoria.cdcategoria = hd_chamado.cdcategoria\ninner join ad_usuario on ad_usuario.cdusuario = hd_chamado.cdresponsavel\nwhere cdsituacao not in ('7', '8')\nand hd_categoria.cdcategoriasuperior = '1098'\norder by CHAMADO"
      }
     ]
    }
   ]
  },
  {
   "title": "AVALIAÇÕES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVALIADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ISNULL(SUM(CASE WHEN\nhc.cdalternativa=1 or\nhc.cdalternativa=5 or\nhc.cdalternativa=2 or\nhc.cdalternativa=3 THEN 1 END),0) as \"Quantidade\"\nfrom ps_resposta hch\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59' and cdchamado is not null"
      }
     ]
    },
    {
     "title": "NÃO AVALIADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ((select COUNT(cdchamado)\nfrom hd_chamado\nwhere dttermino BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand (cdsituacao = '7' or cdsituacao = '5')) - ISNULL(SUM(CASE WHEN\nhc.cdalternativa=1 or\nhc.cdalternativa=5 or\nhc.cdalternativa=2 or\nhc.cdalternativa=3 THEN 1 END),0))\nfrom ps_resposta hch\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand cdchamado is not null"
      }
     ]
    },
    {
     "title": "[CHAT] AVALIADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 10, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ISNULL(SUM(CASE WHEN\nhc.cdalternativa=1 or\nhc.cdalternativa=5 or\nhc.cdalternativa=2 or\nhc.cdalternativa=3 THEN 1 END),0) as \"Quantidade\"\nfrom ps_resposta hch\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere hch.dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59' \nand hch.cdatendimento is not null"
      }
     ]
    },
    {
     "title": "[CHAT] NÃO AVALIADOS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (count(*) - (select ISNULL(SUM(CASE WHEN\nhc.cdalternativa=1 or\nhc.cdalternativa=5 or\nhc.cdalternativa=2 or\nhc.cdalternativa=3 THEN 1 END),0) as \"Quantidade\"\nfrom ps_resposta hch\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere hch.dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hch.cdatendimento is not null))\nfrom hd_sessaoatendimento\nwhere dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'"
      }
     ]
    },
    {
     "title": "AVALIAÇÃO DETALHADA",
     "type": "table",
     "gridPos": { "h": 16, "w": 10, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select\nnmusuario as \"Colaborador\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=1 THEN 1 END),0) as \"Ótimo\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=5 THEN 1 END),0) as \"Bom\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=2 THEN 1 END),0) as \"Regular\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=3 THEN 1 END),0) as \"Ruim\",\nISNULL(SUM(CASE WHEN hc.cdalternativa in (1, 2, 3, 5) THEN 1 END),0) as \"Total\"\nfrom ps_resposta hch\nINNER JOIN hd_chamado hdc ON hch.cdchamado = hdc.cdchamado\nINNER JOIN ad_usuario adu ON adu.cdusuario = hdc.cdresponsavel\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere hch.dtresposta BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hch.cdchamado is not null\ngroup by nmusuario\norder by \"Ótimo\" desc, \"Bom\" desc, \"Regular\" desc, \"Colaborador\""
      }
     ]
    },
    {
     "title": "[CHAT] AVALIAÇÃO DETALHADA ",
     "type": "table",
     "gridPos": { "h": 16, "w": 14, "x": 10, "y": 9 },
     "targets": [
      {
       "rawSql": "select\nnmusuario as \"Colaborador\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=1 THEN 1 END),0) as \"Ótimo\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=5 THEN 1 END),0) as \"Bom\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=2 THEN 1 END),0) as \"Regular\",\nISNULL(SUM(CASE WHEN hc.cdalternativa=3 THEN 1 END),0) as \"Ruim\",\nISNULL(SUM(CASE WHEN hc.cdalternativa in (1, 2, 3, 5) THEN 1 END),0) as \"Total\"\nfrom ps_resposta hch\nINNER JOIN hd_sessaoatendimento hds ON hch.cdatendimento = hds.cdatendimento\nINNER JOIN ad_usuario adu ON adu.cdusuario = hds.cdatendente\nINNER JOIN ps_respostaalternativa hc ON hch.cdresposta = hc.cdresposta\nwhere hch.dtresposta  between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hch.cdatendimento is not null\ngroup by nmusuario\norder by \"Ótimo\" desc, \"Bom\" desc, \"Regular\" desc, \"Colaborador\""
      }
     ]
    }
   ]
  },
  {
   "title": "CATEGORIAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CANCELADOS X MOTIVO",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "select cham.cdchamado as \"N CHAMADO\",\nnmusuario as \"RESPONSAVEL\",\nnmcliente as \"EMPRESA\",\nSUBSTRING(dsacompanhamento,25,600) as \"MOTIVO\"\nfrom hd_chamado cham \ninner join ad_cliente on ad_cliente.cdcliente = cham.cdcliente\njoin hd_situacao hs on(hs.cdsituacao = cham.cdsituacao)\njoin hd_localidade loc on(loc.cdlocalidade = cham.cdlocalidade) \njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado) \nwhere 1=1\nand cham.dtchamado BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hs.cdsituacao = 8\nand dsacompanhamento like '%Chamado cancelado%'"
      }
     ]
    },
    {
     "title": "CANCELADOS X FECHADOS",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "select hs.nmsituacao as \"TIPO\",\n     COUNT(hs.nmsituacao) as \"QUANTIDADE\"\nfrom hd_chamado cham\njoin hd_situacao hs on (hs.cdsituacao = cham.cdsituacao) \nwhere 1=1\nand dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nand hs.cdsituacao in ('7','8')\ngroup by  hs.nmsituacao"
      }
     ]
    },
    {
     "title": "ABERTOS X ENCERRADOS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT abertos.data as time,\n       encerrados.data as time,\n       ISNULL(abertos.\"data\", encerrados.\"data\"), ISNULL(\"abertos\",0) as \"abertos\", ISNULL(\"encerrados\",0) as \"encerrados\"\nFROM\n(SELECT CONVERT(date,dtchamado) as \"data\", count(cdchamado) as \"abertos\"\nFROM hd_chamado\nWHERE dtchamado between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nGROUP BY CONVERT(date,dtchamado)) as abertos\nFULL OUTER JOIN\n(SELECT CONVERT(date,dttermino) as \"data\", count(cdchamado) as \"encerrados\"\nFROM hd_chamado\nWHERE dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nGROUP BY CONVERT(date,dttermino)) as encerrados\nON abertos.\"data\"=encerrados.\"data\""
      }
     ]
    },
    {
     "title": "SUSPENSOS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \nhd_motivosuspenso.nmmotivosuspenso, COUNT(hd_motivosuspenso.nmmotivosuspenso) AS qtdSuspenso\nFROM hd_chamado\nLEFT JOIN hd_suspenso on hd_suspenso.cdchamado = hd_chamado.cdchamado and hd_suspenso.dtreativacao is null\nLEFT JOIN hd_situacao ON hd_situacao.cdsituacao = hd_chamado.cdsituacao\nLEFT JOIN hd_motivosuspenso on hd_motivosuspenso.cdmotivosuspenso = hd_suspenso.cdmotivosuspenso\nWHERE hd_motivosuspenso.nmmotivosuspenso is not null\nand hd_situacao.nmsituacao = 'Suspenso'\nGROUP BY hd_motivosuspenso.nmmotivosuspenso\nORDER BY qtdSuspenso desc"
      }
     ]
    },
    {
     "title": "ENCERRADOS X ATENDIMENTOS",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "select nmusuario as \"COLABORADOR\", cast(COUNT(cdresponsavel) as integer) as \"ENCERRADOS\",\n(select cast(COUNT(cdresponsavel) as integer)\nfrom hd_chamado hdc\nINNER JOIN ad_usuario adu ON hdc.cdresponsavel = adu.cdusuario\nwhere (cdsituacao = '2' or cdsituacao = '3') and adu.nmusuario=adu1.nmusuario\ngroup by cdresponsavel, nmusuario) as \"EM ATENDIMENTO\"\nfrom hd_chamado hdc\nINNER JOIN ad_usuario adu1 ON hdc.cdresponsavel = adu1.cdusuario\nwhere (cdsituacao = '7' AND hdc.cdcliente != '6' and hdc.cdorigem != '4') and (dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59')\ngroup by nmusuario order by ENCERRADOS desc"
      }
     ]
    },
    {
     "title": "LOCALIDADE",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \ncount(distinct(cham.cdchamado)) as value,\nloc.nmlocalidade as metric\nfrom hd_chamado cham \njoin hd_situacao hs on(hs.cdsituacao = cham.cdsituacao)\njoin hd_localidade loc on(loc.cdlocalidade = cham.cdlocalidade) \njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado) \nwhere 1=1\nand cham.dtchamado between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\ngroup by loc.nmlocalidade"
      }
     ]
    },
    {
     "title": "ORIGEM",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \nhdo.nmorigem,\ncount(cham.cdchamado)\nFROM hd_chamado cham\njoin hd_origem hdo on(hdo.cdorigem = cham.cdorigem)\nWHERE 1=1\nAND dttermino BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\ngroup by hdo.nmorigem\n"
      }
     ]
    },
    {
     "title": "UF",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \n      ad_uf.sguf, \n      cast(COUNT(hdc.cdcliente) as integer)\nfrom hd_chamado hdc\nINNER JOIN ad_cliente ON hdc.cdcliente = ad_cliente.cdcliente\nINNER JOIN ad_cidade ON ad_cliente.cdcidade = ad_cidade.cdcidade\nINNER JOIN ad_uf ON ad_cidade.cduf = ad_uf.cduf\nwhere (ad_uf.sguf != null or ad_uf.sguf != '')\nand (hdc.cdsituacao = '7' or hdc.cdsituacao = '5')\nand hdc.dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\ngroup by ad_uf.sguf"
      }
     ]
    },
    {
     "title": "TIPO",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \nCASE\nwhen cdtipochamado=32 then 'Incidente'\nwhen cdtipochamado=33 then 'Requisição'\nwhen cdtipochamado=38 then 'Não Classificado'\nwhen cdtipochamado=39 then 'Mudança'\nwhen cdtipochamado=18 then '[Depreciado]'\nEND as \"Tipo de Chamado\",\nCOUNT(cdtipochamado) as \"Quantidade\"\nfrom hd_chamado\nwhere 1=1\nand cdsituacao = '7'\nand (dttermino BETWEEN '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59')\ngroup by cdtipochamado\norder by \"Quantidade\" desc"
      }
     ]
    },
    {
     "title": "STATUS",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 9, "x": 7, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select convert(date, getdate()) as time, \ncount(distinct(cham.cdchamado)) as value,\nhs.nmsituacao as metric\nfrom hd_chamado cham \njoin hd_situacao hs on(hs.cdsituacao = cham.cdsituacao)\njoin hd_localidade loc on(loc.cdlocalidade = cham.cdlocalidade) \njoin ad_usuario usu on (usu.cdusuario=cham.cdresponsavel) \njoin hd_acompanhamento hda on (hda.cdchamado=cham.cdchamado) \nwhere 1=1\nand cham.dtchamado between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\ngroup by hs.nmsituacao"
      }
     ]
    }
   ]
  },
  {
   "title": "RANKING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP 10 EMPRESAS",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "select TOP 10 ad_cliente.nmcliente as \"EMPRESA\", cast(COUNT(hdc.cdcliente) as integer) as \"QUANTIDADE\",\nROUND(cast(COUNT(hdc.cdcliente) as float) /\nCAST((select cast(COUNT(hdc.cdcliente) as integer)\nfrom hd_chamado hdc\nwhere (hdc.cdsituacao = '7' or hdc.cdsituacao = '5') and hdc.dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59') as float)*100, 2) as \"PORCENTAGEM\"\nfrom hd_chamado hdc\nINNER JOIN ad_cliente ON hdc.cdcliente = ad_cliente.cdcliente\nwhere (hdc.cdsituacao = '7' or hdc.cdsituacao = '5') and hdc.dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\ngroup by ad_cliente.nmcliente\norder by \"QUANTIDADE\" desc"
      }
     ]
    },
    {
     "title": "TOP CATEGORIA",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT nmcategoria + ' > ' + t2.categoria AS CATEGORIA, t2.QUANTIDADE FROM\n(SELECT nmcategoria + ' > ' + t1.categoria AS CATEGORIA, hd_categoria.cdcategoriasuperior, t1.quantidade FROM\n(SELECT TOP 15 nmcategoria as CATEGORIA, cdcategoriasuperior, COUNT(cdchamado) as QUANTIDADE\nFROM hd_chamado\nINNER JOIN hd_categoria ON hd_categoria.cdcategoria = hd_chamado.cdcategoria\nWHERE (cdsituacao = '7' OR cdsituacao = '5')\nAND dttermino between '${__from:date:YYYY-MM-DD} 00:00:00' and '${__to:date:YYYY-MM-DD} 23:59:59'\nGROUP BY hd_categoria.nmcategoria, hd_categoria.cdcategoriasuperior\nORDER BY QUANTIDADE desc) AS t1\nINNER JOIN hd_categoria ON hd_categoria.cdcategoria = t1.cdcategoriasuperior) AS t2\nINNER JOIN hd_categoria ON hd_categoria.cdcategoria = t2.cdcategoriasuperior"
      }
     ]
    }
   ]
  },
  {
   "title": "SUSPENSOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SUSPENSOS AGUARDANDO DESENVOLVIMENTO",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "select * from (SELECT hd_chamado.cdchamado as \"N CHAMADO\", \nad_cliente.nmcliente as \"EMPRESA\", \nnmusuario as \"RESPONSAVEL\", \nhd_chamado.nmtitulochamado as \"TITULO\",\ncase \n WHEN SUBSTRING(nmtitulochamado, PATINDEX('%#[0-9]%', nmtitulochamado), 6) like '#%' then SUBSTRING(nmtitulochamado, PATINDEX('%#[0-9]%', nmtitulochamado), 6)\n WHEN SUBSTRING(nmtitulochamado, PATINDEX('%#[0-9]%', nmtitulochamado), 6) not like '#%' then 'SEM ATIVIDADE'\nEND as ATIVIDADE\n   FROM hd_chamado\n   LEFT JOIN ad_usuario ON hd_chamado.cdresponsavel = ad_usuario.cdusuario\n   LEFT JOIN hd_situacao ON hd_situacao.cdsituacao = hd_chamado.cdsituacao\n   LEFT JOIN ad_cliente ON hd_chamado.cdcliente = ad_cliente.cdcliente\n   LEFT JOIN hd_suspenso on hd_suspenso.cdchamado = hd_chamado.cdchamado and hd_suspenso.dtreativacao is null\n   LEFT JOIN hd_motivosuspenso on hd_motivosuspenso.cdmotivosuspenso = hd_suspenso.cdmotivosuspenso\nWHERE 1=1\nand nmsituacao = 'Suspenso'\nand (hd_suspenso.cdmotivosuspenso = '5' or hd_suspenso.cdmotivosuspenso = '9'))  dados\nwhere 1=1\norder by \"N CHAMADO\" asc "
      }
     ]
    }
   ]
  }
 ]
}